---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: immich
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
