---
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: immich
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_DATABASE_NAME: {{ .Values.secrets.dbDatabaseName | quote }}
