---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: {{ include "immich.ns" . }}
  labels:
    app: immich
    component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: immich
    component: server
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 2283
      protocol: TCP
      {{- if eq .Values.server.service.type "NodePort" }}
      nodePort: {{ .Values.server.service.nodePort }}
      {{- end }}
